// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phppdhsozkpsquxlfezg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBocHBkaHNvemtwc3F1eGxmZXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NzIwOTcsImV4cCI6MjA5MDA0ODA5N30.4Gv2-KnfdnBLfzen9HZYvXD5vnmUPtn6MySTF9YhqC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});