/**
 * Test helpers — expose internal functions for testing without
 * importing Edge Function modules directly (Deno vs Node mismatch).
 *
 * These mirror the logic inside the Edge Functions so we can test
 * them in a Node/Vitest environment.
 */

// ─── System prompt builder (mirrors opportunity-chat/index.ts) ────────────────

export function buildSystemPromptForTest(
  opportunity: {
    title: string;
    description: string;
    target_market: string;
    problem_statement?: string;
  },
  research: {
    opportunityScore?: number;
    verdict?: string;
    briefSummary?: string;
    painPoints?: string[];
    demandSignals?: string[];
    competitors?: { name: string; description: string; gap: string }[];
    marketGaps?: string[];
    risks?: string[];
    analogousMarkets?: string[];
    totalDataPoints?: number;
    dataQuality?: string;
  },
  messageCount: number
): string {
  const painPointsList = (research.painPoints || []).slice(0, 5).map(p => `  - ${p}`).join('\n');
  const gapsList = (research.marketGaps || []).slice(0, 4).map(g => `  - ${g}`).join('\n');
  const competitorsList = (research.competitors || []).slice(0, 4)
    .map(c => `  - ${c.name}: ${c.description} (Gap: ${c.gap})`).join('\n');
  const demandList = (research.demandSignals || []).slice(0, 4).map(d => `  - ${d}`).join('\n');

  const scoreContext = research.opportunityScore
    ? `The FounderLens research engine scored this opportunity ${research.opportunityScore}/100 (${research.verdict || 'moderate'} signal).`
    : 'The opportunity has been reviewed by the FounderLens research engine.';

  const proposalReadiness = messageCount >= 6
    ? '\n\nThe founder has provided substantial context. Proactively suggest generating the proposal if all key sections are covered.'
    : '';

  return `You are the FounderLens Idea Coach — a senior startup advisor embedded in FounderLens.

## OPPORTUNITY BEING COACHED
Title: "${opportunity.title}"
Description: ${opportunity.description}
Target Market: ${opportunity.target_market}
${opportunity.problem_statement ? `Problem: ${opportunity.problem_statement}` : ''}

## RESEARCH FINDINGS (from FounderLens Research Engine)
${scoreContext}
Data Points Analyzed: ${research.totalDataPoints || 0} (${research.dataQuality || 'moderate'} quality)
${research.briefSummary ? `\nResearch Summary: ${research.briefSummary}` : ''}

### Evidence of Demand
${demandList || '  - Limited direct demand signals found'}

### Pain Points Found
${painPointsList || '  - Not yet identified from community data'}

### Current Competitors
${competitorsList || '  - No major direct competitors identified (potential market gap)'}

### Market Gaps
${gapsList || '  - To be explored in conversation'}${proposalReadiness}`;
}

// ─── Proposal extractor (mirrors OpportunityChat.tsx) ─────────────────────────

export function extractProposalJson(content: string): object | null {
  const match = content.match(/```proposal-json\n([\s\S]*?)```/);
  if (!match) return null;
  try { return JSON.parse(match[1]); } catch { return null; }
}

// ─── Markdown generator (mirrors ProductProposalModal.tsx) ───────────────────

export function generateMarkdown(proposal: any, fallbackTitle: string): string {
  const lines: string[] = [];
  lines.push(`# ${proposal.productName || fallbackTitle}`);
  if (proposal.oneLiner) lines.push(`\n> ${proposal.oneLiner}`);
  if (proposal.problemStatement) { lines.push('\n## Problem'); lines.push(proposal.problemStatement); }
  if (proposal.targetUser?.persona) lines.push(`\n## Target User\n**Persona:** ${proposal.targetUser.persona}`);
  if (proposal.solution?.uniqueDifferentiator) lines.push(`\n**Differentiator:** ${proposal.solution.uniqueDifferentiator}`);
  if (proposal.mvpScope?.mustHave?.length) {
    lines.push('\n## MVP Scope\n**Must Have:**');
    proposal.mvpScope.mustHave.forEach((f: string) => lines.push(`- [ ] ${f}`));
  }
  if (proposal.monetization) {
    lines.push('\n## Monetization');
    if (proposal.monetization.model) lines.push(`**Model:** ${proposal.monetization.model}`);
    if (proposal.monetization.pricing) lines.push(`**Pricing:** ${proposal.monetization.pricing}`);
  }
  if (proposal.researchBacking) {
    lines.push('\n---');
    lines.push(`*Generated by FounderLens · Score: ${proposal.researchBacking.opportunityScore || 'N/A'}/100 · ${proposal.researchBacking.dataPoints || 0} data points*`);
  }
  return lines.join('\n');
}

// ─── Evidence score (mirrors validate-opportunity-research scoring) ───────────

export function computeEvidenceScore(data: {
  redditPostCount: number;
  webCitationCount: number;
  competitorAppCount: number;
  analogousCitationCount: number;
  competitorWebCitationCount: number;
}): number {
  let score = 30;

  if (data.redditPostCount === 0) score += 0;
  else if (data.redditPostCount <= 3) score += 5;
  else if (data.redditPostCount <= 10) score += 12;
  else if (data.redditPostCount <= 20) score += 18;
  else score += 22;

  if (data.webCitationCount === 0) score -= 5;
  else if (data.webCitationCount >= 4) score += 10;
  else score += 5;

  if (data.competitorAppCount === 0) score += 15;
  else if (data.competitorAppCount <= 3) score += 8;
  else score += 5;

  if (data.analogousCitationCount >= 4) score += 15;
  else if (data.analogousCitationCount >= 1) score += 8;

  if (data.competitorWebCitationCount >= 3) score += 8;
  else if (data.competitorWebCitationCount >= 1) score += 4;

  return Math.min(95, Math.max(15, score));
}

// ─── CEO notification decision (mirrors notify-ceo-new-signals) ───────────────

export function shouldNotifyCeo(workflow: {
  paperclip_company_id?: string | null;
}): boolean {
  return !!workflow.paperclip_company_id;
}

export function briefingIssuePriority(opportunityScore: number): 'high' | 'medium' | 'low' {
  return opportunityScore >= 70 ? 'high' : opportunityScore >= 45 ? 'medium' : 'low';
}
